language: node_js

node_js:
- '10.6.0'
- '5'
- '6'
- '7'
- '8'
- '9'

sudo: false

# Allow greenkeeper to commit package-lock.json via greenkeeper-lockfile.
# greenkeeper-lockfile-upload will run only on the first listed node_js version.
# We still explicitly skip all greenkeeper-lockfile related steps on Node.js
# versions 4-7 because the build for the first GK commit (that updates
# package.json) will fail on those versions in the greenkeeper-lockfile-update
# step.
before_install: '[[ $(node -v) =~ ^v4.*$ ]] || [[ $(node -v) =~ ^v5.*$ ]] || [[ $(node -v) =~ ^v6.*$ ]] || [[ $(node -v) =~ ^v7.*$ ]] || npm install -g greenkeeper-lockfile'
before_script: '[[ $(node -v) =~ ^v4.*$ ]] || [[ $(node -v) =~ ^v5.*$ ]] || [[ $(node -v) =~ ^v6.*$ ]] || [[ $(node -v) =~ ^v7.*$ ]] || greenkeeper-lockfile-update'
after_script: '[[ $(node -v) =~ ^v4.*$ ]] || [[ $(node -v) =~ ^v5.*$ ]] || [[ $(node -v) =~ ^v6.*$ ]] || [[ $(node -v) =~ ^v7.*$ ]] || greenkeeper-lockfile-upload'

env:
  global:
    secure: GJS1HncilhBL5EOtWYCTeblDN2P0VHNTRoqrBAJeaMNA4m3an12HfcLqXTDk+PoOViPwYoiEWTo2TP9i7ryTUoW59U1WqmzqLujxcWDol8uewGg1SGFv/fiHMhMsgouWhbqUp9u3AOjevLpn7fCTACKxb1BsPhbDR3eeJfnxb1g=
